### PR TITLE
Edited TrafficSimulation.py 

### PR DESCRIPTION
**Pull request by deleoa5**
Changed to catch with "if" statement instead of "assert" to remove inactive code. 
Code now returns if conditions aren't met.

### CODE REVIEW

**Review by MacTireBan — COMMENTED** [review]
The if-statements should be indented so they happen within the while loops. The point of them is to prevent the index from exceeding the allowable range of values.

**Review by L-u-t-o — APPROVED** [review]
looks good. Keep in mind most of the program is running off of TrafficSimulation2.py; as it is properly parsing file data

**Comment by deleoa5** [comment]
> The if-statements should be indented so they happen within the while loops. The point of them is to prevent the index from exceeding the allowable range of values.

Done.

**Comment by deleoa5** [comment]
> looks good. Keep in mind most of the program is running off of TrafficSimulation2.py; as it is properly parsing file data

@L-u-t-o sounds good. We can use the V1 as a backup then and update it as necessary in the future if something goes wrong. Thanks!

**Review by MacTireBan — APPROVED** [review]

**Pull request merged**
