### PR TITLE
Upload 3.3

### PR DESCRIPTION
**Pull request by ks-moss**
Just the draft

### CODE REVIEW

**Comment by devyngilliam** [comment]
I would be more descriptive when issuing pull requests Kris.

**Comment by L-u-t-o** [comment]
Draft looks good -- No conflicts to reject.

**Review by L-u-t-o — APPROVED** [review]
Draft looks good -- no conflicts to reject

**Review by Dashtine — APPROVED** [review]
Code meets (whether hard coded or commented out) necessary procedures required for 3.3 of the project. It could be updated and completed once 3.1 & 3.2 sections are done. 
Pull request approved.

**Review by GusEsplin — COMMENTED** [review]
Everything added looks good, but AutomaticSimulation.py could use more documentation. I am currently working on implementing AutomaticSimulation.py as well, so I will add the documentation.

**Pull request merged**
