### PR TITLE
Created some tests

### PR DESCRIPTION
**Pull request by MacTireBan**
Added test for automaticsimulation. I wasn't sure how to view the coverage file, though. Maybe someone can check that it works as intended?

### CODE REVIEW

**Review by GusEsplin — APPROVED** [review]
Thank you for contributing to the unit testing! This will bring us closer to our branch coverage goal.

**Review by L-u-t-o — APPROVED** [review]
Thank you for the unit test update. Approved

**Review by Proxhi — APPROVED** [review]
Nice addition to the unit tests!

**Review by angflores — APPROVED** [review]
approving

**Pull request merged**
