### PR TITLE
Added BusStop Button and buildings / additional changes

### PR DESCRIPTION
**Pull request by L-u-t-o**
**3dGraphics.py**

- 'Add Bus Stop' button added which places a bus stop randomly on one of the available roads
- timePassed changes... hard-to-solve problem tracking timePassing for bus (I created small workaround)

**FunctionCallSimulation**

- added buildings for asthetics
- removed wireframe white color and road frame color (set to clear)

### CODE REVIEW

**Review by angflores — APPROVED** [review]
Yay, RTC here we come! Thanks for adding.

**Review by GusEsplin — COMMENTED** [review]
I have reviewed the files changed and found that you're additions are beneficial to the codebase.

**Review by ks-moss — CHANGES_REQUESTED** [review]
timePassed must set back to 0 when  !(busStopEntity.intersects(vehicle))
Otherwise, the bus won't make another stop 
Screenshot 2023-04-19 at 7 47 38 PM


I saw that you did set timePassed to 0 at the top but that's not going to perform well. Try my code

**Review by ks-moss — APPROVED** [review]
I will make changes. I still see something that's not right

**Pull request merged**
