### PR TITLE
Various adjustments to TrafficSimulation2 and VehicleGen

### PR DESCRIPTION
**Pull request by L-u-t-o**
Corrected slight errors and added allowance of xml files that do not have "type" feature yet. Added VehicleGenerator to adjust vehicleList to include new vehicles. Added sample xml files for vehicleGenerator

### CODE REVIEW

**Review by devyngilliam — APPROVED** [review]
Thank you for submitting the pull request to the project. I have reviewed the changes you made and can see that you have done an excellent job of correcting slight errors and making important updates to the code. I also appreciate the addition of VehicleGenerator to adjust the vehicleList to include new vehicles, as well as the sample XML files for VehicleGenerator.

Your contributions will certainly improve the overall functionality and usability of the project, and we appreciate your efforts in making these changes.

**Comment by devyngilliam** [comment]
Again, great job!

**Review by devyngilliam — APPROVED** [review]
Pasting last comment again:

Thank you for submitting the pull request to the project. I have reviewed the changes you made and can see that you have done an excellent job of correcting slight errors and making important updates to the code. I also appreciate the addition of VehicleGenerator to adjust the vehicleList to include new vehicles, as well as the sample XML files for VehicleGenerator.

Your contributions will certainly improve the overall functionality and usability of the project, and we appreciate your efforts in making these changes.

**Comment by devyngilliam** [comment]
Not sure why last review of mine didn't publish.

**Review by MacTireBan — APPROVED** [review]

**Pull request merged**
