### PR TITLE
Vehicle Generator/Error Message/Car Type

### PR DESCRIPTION
**Pull request by 050cal**
- Added error checking and error message for the elements and element attributes
- Updated parser to add Vehicle Generator to sim
- Updated parser to read in car type for Vehicles

### CODE REVIEW

**Review by L-u-t-o — APPROVED** [review]
great error checking and vehicleGenerator addition. some execution errors are showing on my end but I will check solutions as the errors may be on my end

**Comment by 050cal** [comment]
> great error checking and vehicleGenerator addition. some execution errors are showing on my end but I will check solutions as the errors may be on my end

**Comment by devyngilliam** [comment]
Great addition with the error checking for the file. The 3.2 team will also implement these additions to the TrafficLightSimulation.py file. Keep up the great work!

**Comment by MacTireBan** [comment]
Seems legit

**Review by MacTireBan — APPROVED** [review]

**Comment by 050cal** [comment]
> great error checking and vehicleGenerator addition. some execution errors are showing on my end but I will check solutions as the errors may be on my end

I just noticed a stray comma in there now that it is merged but it seemed to be executing fine on my end. Let me know if there is something in particular giving you problems.

**Pull request merged**
