### PR TITLE
Added bus stop functionality to TrafficSimulation2 file, updated xml test file

### PR DESCRIPTION
**Pull request by L-u-t-o**
Implementing parsing of BUSSTOP data from xml file to include road location of stop, position on road, and waiting time for for bus. Adds list of bus stops as well.

### CODE REVIEW

**Comment by ks-moss** [comment]
More input data were added. As sequence, added a function to read  in the data. Good work

**Review by ks-moss — COMMENTED** [review]
More input data were added. As sequence, added a function to read in the data. Good work

**Review by devyngilliam — APPROVED** [review]
This pull request adds valuable functionality to the codebase by implementing parsing of BUSSTOP data from an xml file. The addition of road location of stop, position on road, and waiting time for buses provides crucial information for users and enhances the overall user experience. Additionally, the inclusion of a list of bus stops is a useful feature that will help users easily navigate the available stops.

The implementation of this functionality appears to be well-structured and organized, with clear and concise code that is easy to read and understand. The new code also appears to integrate seamlessly with the existing codebase.

Overall, this pull request is a valuable addition to the project, and I highly recommend it for approval.

**Review by ks-moss — COMMENTED** [review]
More input data were added. As sequence, added a function to read in the data. Good work

**Review by ks-moss — APPROVED** [review]
More input data were added. As sequence, added a function to read in the data. Good work

**Pull request merged**
