### PR TITLE
Update comments and alightment. Still waiting 1.5

### PR DESCRIPTION
**Pull request by ks-moss**
Update comments and alightment. 
Note: I'm still waiting for 1.5 to be complete, so I can continue working on it
Line 80 will need the implement of case 1.5, which will select the road from the list.
Gus and I will be working on this part.

### CODE REVIEW

**Comment by deleoa5** [comment]
Good edits so far, this will be useful in the simulation for intersections once 1.5 is complete.

Out of curiosity, will this need to access vehicle information like the length? If not no worries.

**Review by deleoa5 — APPROVED** [review]
Good edits so far, this will be useful in the simulation for intersections once 1.5 is complete.

Out of curiosity, will this need to access vehicle information like the length? If not no worries.

**Review by L-u-t-o — APPROVED** [review]
Just a general alignment and comment update -- i can see no conflicts arising. Looks good to me.

**Comment by ks-moss** [comment]
> Good edits so far, this will be useful in the simulation for intersections once 1.5 is complete.
> 
> Out of curiosity, will this need to access vehicle information like the length? If not no worries.
This will need access current poison of the vehicle

**Pull request merged**
